# TRATAMENTO DE ERROS
x = 10

try:
    print(x)

# except: caso ocorra um erro
except :
    print("Ocorreu um erro")

# finally: sempre executado
finally:
    print("Fim do programa")